// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCpS0Siq1v9EgBdqKUXvBNtWuGqlgy9gg',
    appId: '1:556388172573:web:fca64e0689abf642f6d7f4',
    messagingSenderId: '556388172573',
    projectId: 'mark-it-975b7',
    authDomain: 'mark-it-975b7.firebaseapp.com',
    storageBucket: 'mark-it-975b7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0RkK6VajYlsrf_IrdmjPPgtv8C4Dw5Jc',
    appId: '1:556388172573:android:30ac6125fec0903bf6d7f4',
    messagingSenderId: '556388172573',
    projectId: 'mark-it-975b7',
    storageBucket: 'mark-it-975b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW1GG24SV8lyqqF8KR4PmIs4f-Y_SVVBs',
    appId: '1:556388172573:ios:91767336947c3efdf6d7f4',
    messagingSenderId: '556388172573',
    projectId: 'mark-it-975b7',
    storageBucket: 'mark-it-975b7.appspot.com',
    iosBundleId: 'com.example.markIt',
  );
}
